# PROD docker compose script

services:
  poketurl-service:
    image: poketurl:2026.6
    build: .
    container_name: poketurl-service
    volumes:
      # use bind mount
      - /opt/poketurl/data:/app/data
    environment:
      DB_URL: "jdbc:sqlite:/app/data/poketurl-db.sqlite"
      BASE_PATH: ${BASE_PATH:-}
      RATE_LIMIT: ${RATE_LIMIT:-false}

    # hardening
    security_opt:
      - "no-new-privileges=true"
    cap_drop:
      - ALL

    # deployment
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512m
        reservations:
          cpus: '0.5'
          memory: 256m
    restart: on-failure:5
