# LOCAL docker compose script

services:
  poketurl-service:
    image: poketurl:2026.9
    build: .
    container_name: poketurl-service
    volumes:
      # use bind mount
      - ./app/data:/app/data
    ports:
      - 5000:5000
    environment:
      DB_URL: "jdbc:sqlite:/app/data/poketurl-db.sqlite"
      BASE_PATH: ${BASE_PATH:-}

    # hardening
    security_opt:
      - "no-new-privileges=true"
    cap_drop:
      - ALL

    # deployment
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256m
        reservations:
          cpus: '0.5'
          memory: 96m
    restart: on-failure:5
