server:
  port: ${PORT:5000}
  host: 0.0.0.0

# application configs
app:
  basePath: ${BASE_PATH:http://localhost:5000}

# database config
database:
  url: ${DB_URL:jdbc:sqlite:./app/data/poketurl-db.sqlite}
