ktor:
  deployment:
    port: ${PORT:5000}
  application:
    modules:
      - MainKt.module

# application configs
app:
  basePath: ${BASE_PATH:http://localhost:5000}
  database:
    url: ${DB_URL:jdbc:sqlite:./app/data/poketurl-db.sqlite}
  rateLimit:
    enabled: ${RATE_LIMIT:false}
