[versions]
arrow = "2.2.1.1"
exposed = "1.2.0"
kotlin = "2.3.21"
logback = "1.5.21"
sqlite = "3.49.1.0"
cache4k = "0.14.0"


[libraries]
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
arrow-fx-coroutines = { module = "io.arrow-kt:arrow-fx-coroutines", version.ref = "arrow" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
exposed-datetime = { module = "org.jetbrains.exposed:exposed-kotlin-datetime", version.ref = "exposed" }
sqlite = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
cache4k-cache = { module = "io.github.reactivecircus.cache4k:cache4k", version.ref = "cache4k"}

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
